# -*- coding: utf-8 -*-
"""Weather_analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dQ6cDDoLAB9VwbVFtLsxvDqXlfJ7kFV4

#ALFIDO TECH WEATHER ANALYSIS

##ABOUT THE DATASET

## Understanding and Utilizing Weather Data

##Introduction:

Weather data plays a crucial role in our daily lives and various industries, from agriculture to transportation and emergency preparedness. Understanding and effectively utilizing weather data can help individuals and organizations make informed decisions, improve safety, and optimize operations.

##Types of Weather Data:
Weather data encompasses a wide range of information collected from various sources, including meteorological stations, satellites, weather balloons, and weather radars. The key types of weather data include:

a. Temperature: Information about the current and forecasted temperature, which impacts clothing choices, heating and cooling needs, and agricultural practices.

b. Precipitation: Data on rainfall, snowfall, and other forms of precipitation, critical for water resource management, flood forecasting, and agricultural planning.

c. Humidity: Measures the amount of moisture in the air, influencing human comfort, crop health, and weather patterns.

d. Wind Speed and Direction: Wind data is vital for aviation, renewable energy generation, and understanding weather patterns.

e. Atmospheric Pressure: Information about the pressure exerted by the atmosphere, useful for weather predictions and altimeter settings for aviation.

f. Cloud Cover: Indicates the fraction of the sky covered by clouds and helps determine potential rainfall and solar radiation.

g. UV Index: Measures the strength of ultraviolet radiation from the sun, important for skin protection and outdoor activities.

Weather Data Sources:
Weather data comes from a variety of sources, including:

a. National Meteorological Agencies: Government agencies responsible for collecting and disseminating weather information for specific regions or countries.

b. Weather Stations: Ground-based installations that monitor local weather conditions, including temperature, humidity, and precipitation.

c. Satellites: Orbiting satellites capture images and data from space, providing a broader perspective on weather patterns and storms.

d. Weather Radars: Used to detect precipitation, measure wind speed, and identify severe weather events such as tornadoes and thunderstorms.

e. Weather Balloons: Instruments attached to weather balloons collect atmospheric data at different altitudes.

f. Weather Apps and Websites: Online platforms that provide real-time weather updates and forecasts based on data from various sources.

Applications of Weather Data:
Weather data has numerous applications across various industries and activities, including:

a. Agriculture: Farmers use weather data to schedule irrigation, plan planting and harvesting, and mitigate the impact of extreme weather on crops.

b. Transportation: Airlines, shipping companies, and road networks rely on weather data to optimize routes, avoid hazardous conditions, and ensure passenger safety.

c. Renewable Energy: Wind and solar energy generation depend on weather data to predict energy production and manage power grids efficiently.

d. Disaster Preparedness: Weather data is vital for early warning systems and emergency response planning during hurricanes, floods, and other severe weather events.

e. Tourism: Tour operators and travelers use weather forecasts to plan outdoor activities and make the most of their trips.

Challenges in Weather Data Analysis:
While weather data is invaluable, analyzing and interpreting it can be complex due to:

a. Data Volume: Weather data is vast and constantly updating, requiring powerful computing systems for processing and analysis.

b. Data Quality: Ensuring the accuracy and reliability of weather data is crucial, as errors can lead to significant consequences.

c. Forecasting Accuracy: Weather forecasting involves uncertainties, and improving prediction accuracy is an ongoing challenge for meteorologists.

Conclusion:

Weather data is a valuable resource that influences our daily lives and various industries. By understanding the types of weather data, its sources, and its applications, individuals and organizations can harness its power to make informed decisions, enhance safety, and optimize operations in a changing climate.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df= pd.read_csv("weather.csv")

df.head()

df.info()

df.describe()

df.shape

# Check for duplicate rows based on all columns
duplicates = df[df.duplicated()]

#
if not duplicates.empty:
    print("Duplicate Rows except first occurrence:")
    print(duplicates)
else:
    print("No duplicate rows found.")

df.isnull().sum()

from matplotlib import pyplot as plt
import seaborn as sns
_df_5.groupby('Weather').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_4.groupby('Date/Time').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['Date/Time']
  ys = series['Dew Point Temp_C']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_11.sort_values('Date/Time', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Weather')):
  _plot_series(series, series_name, i)
  fig.legend(title='Weather', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Date/Time')
_ = plt.ylabel('Dew Point Temp_C')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['Date/Time']
  ys = series['Rel Hum_%']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_13.sort_values('Date/Time', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Weather')):
  _plot_series(series, series_name, i)
  fig.legend(title='Weather', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Date/Time')
_ = plt.ylabel('Rel Hum_%')

from matplotlib import pyplot as plt
_df_14['Temp_C'].plot(kind='line', figsize=(8, 4), title='Temp_C')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['Weather'].value_counts()
    for x_label, grp in _df_18.groupby('Date/Time')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('Date/Time')
_ = plt.ylabel('Weather')

from matplotlib import pyplot as plt
_df_7.plot(kind='scatter', x='Dew Point Temp_C', y='Rel Hum_%', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_8.plot(kind='scatter', x='Rel Hum_%', y='Wind Speed_km/h', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['Date/Time']
  ys = series['Rel Hum_%']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_13.sort_values('Date/Time', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Weather')):
  _plot_series(series, series_name, i)
  fig.legend(title='Weather', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Date/Time')
_ = plt.ylabel('Rel Hum_%')

from matplotlib import pyplot as plt
_df_17['Wind Speed_km/h'].plot(kind='line', figsize=(8, 4), title='Wind Speed_km/h')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_16['Rel Hum_%'].plot(kind='line', figsize=(8, 4), title='Rel Hum_%')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_15['Dew Point Temp_C'].plot(kind='line', figsize=(8, 4), title='Dew Point Temp_C')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_21['Date/Time'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_21, x='Dew Point Temp_C', y='Date/Time', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_19['Date/Time'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_19, x='Temp_C', y='Date/Time', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_20['Weather'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_20, x='Temp_C', y='Weather', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (15, 1.2 * len(_df_22['Weather'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_22, x='Dew Point Temp_C', y='Weather', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)


